[build-system]
requires = ["flit_core >=3.6.0,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sample_theme"
dynamic = ["version", "description"]

dependencies = ["sphinx ~= 4.0"]
requires-python = ">=3.7"

[project.entry-points]
"sphinx.html_themes" = {sample_theme = "sample_theme"}
